server:
  host: localhost
  port: 8081
  mode: debug
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 60s

database:
  host: 192.168.64.23
  port: 30432
  user: mem_bank_user
  password: mem_bank_password
  dbname: mem_bank
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 5
  max_lifetime: 5m

redis:
  host: 192.168.64.23
  port: 30379
  password: ""
  db: 0
  pool_size: 10
  timeout: 5s

logging:
  level: info
  format: json
  output: stdout
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

ai:
  embedding_model: text-embedding-ada-002
  embedding_dim: 1536
  default_threshold: 0.8
  max_context_length: 4000
  default_importance: 5
  auto_summary: true

security:
  jwt_secret: change-this-secret-in-production
  jwt_expiry: 24h
  bcrypt_cost: 12
  rate_limit: 100
  allowed_origins:
    - http://localhost:3000
    - http://localhost:8080
    - http://127.0.0.1:3000

llm:
  provider: openai
  api_key: ${OPENAI_API_KEY}
  base_url: ""  # Optional, uses OpenAI default if empty
  embedding_model: text-embedding-ada-002
  completion_model: gpt-3.5-turbo
  timeout_seconds: 30
  max_retries: 3
  rate_limit: 100

queue:
  queue_name: mem_bank_jobs
  max_retries: 3
  retry_delay: 30s
  job_timeout: 5m
  result_ttl: 24h
  default_concurrency: 5
  poll_interval: 1s
  cleanup_interval: 1h
  stats_enabled: true
  stats_update_interval: 5m

embedding:
  max_text_length: 8000
  cache_enabled: true
  cache_ttl_minutes: 1440  # 24 hours
  batch_size: 100
  normalize_whitespace: true
  to_lowercase: false
  remove_extra_punctuation: true
  chunk_size: 4000
  chunk_overlap: 200

qdrant:
  enabled: false  # Set to true to use Qdrant instead of PostgreSQL for vector search
  host: localhost
  port: 6334
  collection_name: memories
  vector_size: 1536  # Should match embedding model dimensions
  use_https: false
  api_key: ""  # Optional, for Qdrant Cloud